require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: '3.0'

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
